---

- name: Install helm plugins
  community.kubernetes.helm_plugin:
    plugin_name: "{{ helm_plugin.name | default(omit) }}"
    plugin_path: "{{ helm_plugin.path | default(omit) }}"
    state: "{{ helm_plugin.state | default('present') }}"
  loop: "{{ helm_plugins }}"
  loop_control:
    loop_var: helm_plugin
