---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    molecule_driver: "{{ lookup('env', 'MOLECULE_DRIVER_NAME') }}"
    helm_user: root
    helm_plugins: [{'name': 'diff', 'path': 'https://github.com/databus23/helm-diff', 'version': '3.15.2'}, {'name': 'unittest', 'path': 'https://github.com/helm-unittest/helm-unittest', 'version': 'latest'}]
  tasks:
    - name: Include role 'ansible-role-helm'
      ansible.builtin.include_role:
        name: ansible-role-helm
